# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\balancer.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

from parse import compile

import balancer

class Test():
    text = '''WindBag님이 방에 참가했습니다.
크림빵맛있어님이 방에 참가했습니다.
오민석1님이 방에 참가했습니다.
배고파1님이 방에 참가했습니다.
나 강림 단죄확정님이 방에 참가했습니다.
마뫄유튜브트위치구독도네좋아요님이 방에 참가했습니다.
좀비감자님이 방에 참가했습니다.'''

class TeamUserBox(QtWidgets.QWidget):
    def __init__(self, parent):
        super().__init__()

        self.parent = parent

        self.placeHolder = QtWidgets.QWidget(self.parent)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.placeHolder.sizePolicy().hasHeightForWidth())
        self.placeHolder.setSizePolicy(sizePolicy)

        self.placeHolder.setStyleSheet(
            "QWidget {"
            "    padding-right : 20px;"
            "}")

        self.internalHorizontalLayout = QtWidgets.QHBoxLayout(self.placeHolder)
        self.internalHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.internalHorizontalLayout.setSpacing(0)

        self.pushButton = QtWidgets.QPushButton(self.placeHolder)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)

        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)

        self.pushButton.setFont(font)

        self.pushButton.setStyleSheet(
            "QWidget QWidget QPushButton {"
            "    Text-align : left;\n"
            "}")
        
        self.internalHorizontalLayout.addWidget(self.pushButton)

        self.spacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.internalHorizontalLayout.addItem(self.spacer)

        self.MMRLabel = QtWidgets.QLabel(self.placeHolder)
        self.internalHorizontalLayout.addWidget(self.MMRLabel)

        self.parent.layout().addWidget(self.placeHolder)

class UI_Dialog(object):
    def setupUI(self, Dialog):
        self.dialog = Dialog

        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)

        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setAlignment(QtCore.Qt.AlignTop)

        self.comboBox = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 60))

        self.comboBox.horizontalLayout = QtWidgets.QHBoxLayout(self.comboBox)
        self.comboBox.horizontalLayout.setContentsMargins(0,0,0,0)
        self.comboBox.horizontalLayout.setSpacing(10)
        
        self.label = QtWidgets.QLabel(self.comboBox)
        self.label.setText("이름")
        
        self.textEdit = QtWidgets.QLineEdit(self.comboBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.textEdit.setSizePolicy(sizePolicy)

        self.comboBox.horizontalLayout.addWidget(self.label)
        self.comboBox.horizontalLayout.addWidget(self.textEdit)
        
        self.verticalLayout.addWidget(self.comboBox)

        self.horizontalLayout.addWidget(self.frame)

        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.horizontalLayout.addWidget(self.buttonBox)

        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def accept(self):
        self.dialog.userName = self.textEdit.text()
        self.dialog.accept()
    
class UserBox(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()

        # SizePolicy Setting
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)

        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(10, 10, 140, 30))

        self.userEditButton = QtWidgets.QPushButton(self)
        self.userEditButton.setGeometry(QtCore.QRect(0, 0, 300, 100))

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userEditButton.sizePolicy().hasHeightForWidth())
        self.userEditButton.setSizePolicy(sizePolicy)
        self.userEditButton.setText("")
        self.userEditButton.raise_()
        self.label.raise_()
    
    def setUserName(self, text):
        self.label.setText(text)

class UI_Window(object):
    def __init__(self):
        self.window = None

        self.status = 0

        self.gameType = None
        self.teamType = None

        self.userNum = 0

        self.tmpName = "asdf"
        self.userList = []

        self.crawling_base_url = "https://www.op.gg/multi/query="

    def initSetting(self):
        self.leftButton.setDisabled(True)
        self.rightButton.setDisabled(True)

        self.variableMenu.setCurrentIndex(self.status)
        self.mainWindow.setCurrentIndex(self.status)

    def checkArrowStatus(func):
        def wrapper(self):
            func(self)

            self.leftButton.setDisabled(True)
            self.rightButton.setDisabled(True)

            if self.status == 0:
                if self.gameType is not None:
                    self.rightButton.setEnabled(True)
            elif self.status == 1:
                self.leftButton.setEnabled(True)
            elif self.status == 2:
                self.leftButton.setEnabled(True)
        return wrapper

    @checkArrowStatus
    def leftArrowClick(self):
        self.status = max(0, self.status - 1)
        self.variableMenu.setCurrentIndex(self.status)
        self.mainWindow.setCurrentIndex(self.status)

    @checkArrowStatus
    def rightArrowClick(self):
        self.status = min(2, self.status + 1)
        self.variableMenu.setCurrentIndex(self.status)
        self.mainWindow.setCurrentIndex(self.status)

    @checkArrowStatus
    def gameButtonClick(self):
        self.status += 1
        self.variableMenu.setCurrentIndex(1)
        self.mainWindow.setCurrentIndex(1)

    def addUserClick(self):
        self.dialog = QtWidgets.QDialog()
        tmp = UI_Dialog()
        tmp.setupUI(self.dialog)
        self.dialog.exec()

        if self.dialog.result() == QtWidgets.QDialog.Accepted:
            tmp = UserBox()
            tmp.setUserName(self.dialog.userName)
            self.userPageGridLayout.addWidget(tmp, self.userNum / 2, self.userNum % 2, 1, 1)
            self.userList.append(tmp)
            self.userNum += 1

    def addUser(self, name):
        tmp = UserBox()
        tmp.setUserName(name)
        self.userPageGridLayout.addWidget(tmp, self.userNum / 2, self.userNum % 2, 1, 1)
        self.userList.append(tmp)
        self.userNum += 1

    def sendParsing(self):
        text = self.lineEdit.text().strip()

        self.scrollAreaWidgetContent.setText(text)

        val = text.split("\n")

        p = compile("{}님이 방에 참가했습니다.")

        for line in val:
            result = p.parse(line)
            self.addUser(result[0])

    def setupUI(self, window):
        self.window = window

        window.setObjectName("baseWindow")
        window.resize(1200, 740)
        window.setStyleSheet(
            "QWidget#baseWindow "
            "{"
            "background-color : white;"
            "}")

        self.gridLayout = QtWidgets.QGridLayout(window)
        self.gridLayout.setObjectName("gridLayout")

        self.windowWidget = QtWidgets.QWidget(window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windowWidget.sizePolicy().hasHeightForWidth())
        self.windowWidget.setSizePolicy(sizePolicy)
        self.windowWidget.setObjectName("windowWidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.windowWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")

        self.fixedMenu = QtWidgets.QWidget(self.windowWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixedMenu.sizePolicy().hasHeightForWidth())

        self.fixedMenu.setSizePolicy(sizePolicy)
        self.fixedMenu.setMinimumSize(QtCore.QSize(0, 60))
        self.fixedMenu.setBaseSize(QtCore.QSize(0, 60))
        self.fixedMenu.setObjectName("fixedMenu")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fixedMenu)

        self.leftButton = QtWidgets.QPushButton(self.fixedMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftButton.sizePolicy().hasHeightForWidth())
        self.leftButton.setSizePolicy(sizePolicy)
        self.leftButton.setMinimumSize(QtCore.QSize(60, 60))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftButton.setIcon(icon)
        self.leftButton.setIconSize(QtCore.QSize(30, 30))
        self.leftButton.setObjectName("leftButton")
        self.leftButton.clicked.connect(self.leftArrowClick)
        self.horizontalLayout_2.addWidget(self.leftButton)


        self.rightButton = QtWidgets.QPushButton(self.fixedMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightButton.sizePolicy().hasHeightForWidth())
        self.rightButton.setSizePolicy(sizePolicy)
        self.rightButton.setMinimumSize(QtCore.QSize(60, 60))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightButton.setIcon(icon1)
        self.rightButton.setIconSize(QtCore.QSize(30, 30))
        self.rightButton.setObjectName("rightButton")
        self.rightButton.clicked.connect(self.rightArrowClick)
        self.horizontalLayout_2.addWidget(self.rightButton)

        self.line = QtWidgets.QFrame(self.fixedMenu)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)

        # Upper StackedWidget
        self.variableMenu = QtWidgets.QStackedWidget(self.fixedMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.variableMenu.sizePolicy().hasHeightForWidth())
        self.variableMenu.setSizePolicy(sizePolicy)
        self.variableMenu.setMinimumSize(QtCore.QSize(0, 60))
        self.variableMenu.setStyleSheet(
                "QStackedWidget>QWidget {\n"
                "    background-color : \"white\";\n"
                "}")
        self.variableMenu.setObjectName("variableMenu")

        self.firstMenu = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firstMenu.sizePolicy().hasHeightForWidth())
        self.firstMenu.setSizePolicy(sizePolicy)
        self.firstMenu.setObjectName("firstMenu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.firstMenu)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.variableMenu.addWidget(self.firstMenu)

        self.secondMenu = QtWidgets.QWidget()
        self.secondMenu.setObjectName("secondMenu")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.secondMenu)
        self.horizontalLayout_5.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addUserButton = QtWidgets.QToolButton(self.secondMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addUserButton.sizePolicy().hasHeightForWidth())
        self.addUserButton.setSizePolicy(sizePolicy)
        self.addUserButton.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.addUserButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\addButton.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addUserButton.setIcon(icon2)
        self.addUserButton.setIconSize(QtCore.QSize(32, 32))
        self.addUserButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.addUserButton.setObjectName("addUserButton")
        self.addUserButton.clicked.connect(self.addUserClick)

        self.horizontalLayout_5.addWidget(self.addUserButton)


        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.line_2 = QtWidgets.QFrame(self.secondMenu)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.mmrBalancingButton = QtWidgets.QToolButton(self.secondMenu)
        self.mmrBalancingButton.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mmrBalancingButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\bal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mmrBalancingButton.setIcon(icon3)
        self.mmrBalancingButton.setIconSize(QtCore.QSize(32, 32))
        self.mmrBalancingButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mmrBalancingButton.setObjectName("mmrBalancingButton")
        self.horizontalLayout_5.addWidget(self.mmrBalancingButton)
        self.randomTeamButton = QtWidgets.QToolButton(self.secondMenu)
        self.randomTeamButton.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.randomTeamButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\random.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.randomTeamButton.setIcon(icon4)
        self.randomTeamButton.setIconSize(QtCore.QSize(32, 32))
        self.randomTeamButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.randomTeamButton.setObjectName("randomTeamButton")
        self.horizontalLayout_5.addWidget(self.randomTeamButton)
        self.variableMenu.addWidget(self.secondMenu)

        self.thirdMenu = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thirdMenu.sizePolicy().hasHeightForWidth())
        self.thirdMenu.setSizePolicy(sizePolicy)
        self.thirdMenu.setObjectName("thirdMenu")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.thirdMenu)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem2)
        self.line_3 = QtWidgets.QFrame(self.thirdMenu)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.hboxlayout.addWidget(self.line_3)
        self.clipboradButton = QtWidgets.QToolButton(self.thirdMenu)
        self.clipboradButton.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.clipboradButton.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clipboradButton.setIcon(icon5)
        self.clipboradButton.setIconSize(QtCore.QSize(32, 32))
        self.clipboradButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.clipboradButton.setObjectName("clipboradButton")
        self.hboxlayout.addWidget(self.clipboradButton)
        self.randomTeamButton2 = QtWidgets.QToolButton(self.thirdMenu)
        self.randomTeamButton2.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.randomTeamButton2.setFont(font)
        self.randomTeamButton2.setIcon(icon4)
        self.randomTeamButton2.setIconSize(QtCore.QSize(32, 32))
        self.randomTeamButton2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.randomTeamButton2.setObjectName("randomTeamButton2")
        self.hboxlayout.addWidget(self.randomTeamButton2)
        self.clipboradButton.raise_()
        self.line_3.raise_()
        self.randomTeamButton2.raise_()
        self.variableMenu.addWidget(self.thirdMenu)
        self.horizontalLayout_2.addWidget(self.variableMenu)
        self.verticalLayout.addWidget(self.fixedMenu)

        # Lower StackedWidget
        self.mainWindow = QtWidgets.QStackedWidget(self.windowWidget)
        self.mainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mainWindow.setObjectName("mainWindow")

        # Lower FirstPage
        self.firstPage = QtWidgets.QWidget()
        self.firstPage.setMaximumSize(QtCore.QSize(16777210, 16777215))
        self.firstPage.setStyleSheet(
                "QWidget#firstPage "
                "{"
                "    background-color : \"white\";"
                "}")
        self.firstPage.setObjectName("firstPage")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.firstPage)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # FirstPage LOLButton
        self.a_lol = QtWidgets.QPushButton(self.firstPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a_lol.sizePolicy().hasHeightForWidth())
        self.a_lol.setSizePolicy(sizePolicy)
        self.a_lol.setStyleSheet("border-image : url(\"./league.png\");")
        self.a_lol.setIconSize(QtCore.QSize(2997, 214))
        self.a_lol.setAutoRepeat(False)
        self.a_lol.setAutoDefault(False)
        self.a_lol.setDefault(False)
        self.a_lol.setFlat(False)
        self.a_lol.setObjectName("a_lol")

        self.verticalLayout_2.addWidget(self.a_lol)

        # FirstPage SiegeButton
        self.b_siege = QtWidgets.QPushButton(self.firstPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_siege.sizePolicy().hasHeightForWidth())
        self.b_siege.setSizePolicy(sizePolicy)
        self.b_siege.setStyleSheet("border-image : url(\"./siege.png\");")
        self.b_siege.setText("")
        self.b_siege.setIconSize(QtCore.QSize(0, 0))
        self.b_siege.setObjectName("b_siege")
        self.verticalLayout_2.addWidget(self.b_siege)

        # FirstPage OtherButton
        self.c_other = QtWidgets.QPushButton(self.firstPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c_other.sizePolicy().hasHeightForWidth())
        self.c_other.setSizePolicy(sizePolicy)
        self.c_other.setStyleSheet("border-image : url(\"./other.png\");")
        self.c_other.setObjectName("c_other")
        self.verticalLayout_2.addWidget(self.c_other)
        self.mainWindow.addWidget(self.firstPage)

        self.a_lol.clicked.connect(lambda game="LOL" : self.gameButtonClick(game))
        self.b_siege.clicked.connect(lambda game="Siege" : self.gameButtonClick(game))
        self.c_other.clicked.connect(lambda game="Other" : self.gameButtonClick(game))

        # SecondPage
        self.secondPage = QtWidgets.QWidget()
        self.secondPage.setStyleSheet(
                "QWidget#secondPage {"
                "    background-color : \"white\";"
                "}")
        self.secondPageHorizontalLayout = QtWidgets.QHBoxLayout(self.secondPage)

        # SecondPage userPage
        self.userPage = QtWidgets.QWidget(self.secondPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.userPage.sizePolicy().hasHeightForWidth())
        self.userPage.setSizePolicy(sizePolicy)

        # UserPage's GridLayout
        self.userPageGridLayout = QtWidgets.QGridLayout(self.userPage)

        # SecondPage_Line
        self.SecondPage_Line = QtWidgets.QFrame(self.secondPage)
        self.SecondPage_Line.setFrameShape(QtWidgets.QFrame.VLine)
        self.SecondPage_Line.setFrameShadow(QtWidgets.QFrame.Sunken)

        # SecondPage chatPage
        self.chatPage = QtWidgets.QWidget(self.secondPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatPage.sizePolicy().hasHeightForWidth())
        self.chatPage.setSizePolicy(sizePolicy)

        self.chatPageGridLayout = QtWidgets.QGridLayout(self.chatPage)
        self.chatPageGridLayout.setVerticalSpacing(0)

        self.scrollArea = QtWidgets.QScrollArea(self.chatPage)
        self.scrollArea.setWidgetResizable(True)

        self.scrollAreaWidgetContent = QtWidgets.QLabel()
        self.scrollAreaWidgetContent.setAlignment(QtCore.Qt.AlignTop)
        self.scrollAreaWidgetContent.setText("")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        self.scrollAreaWidgetContent.setSizePolicy(sizePolicy)

        self.scrollArea.setWidget(self.scrollAreaWidgetContent)

        self.chatPageGridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        # Contents in TextEditPlaceHolder
        self.chatTextEditPlaceHolder = QtWidgets.QWidget(self.chatPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatTextEditPlaceHolder.sizePolicy().hasHeightForWidth())
        self.chatTextEditPlaceHolder.setSizePolicy(sizePolicy)
        self.chatTextEditPlaceHolder.setMinimumSize(QtCore.QSize(0, 60))
        self.chatTextEditPlaceHolderHorizontalLayout = QtWidgets.QHBoxLayout(self.chatTextEditPlaceHolder)
        self.chatTextEditPlaceHolderHorizontalLayout.setContentsMargins(0, -1, 0, -1)

        self.lineEdit = QtWidgets.QLineEdit(self.chatTextEditPlaceHolder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.chatTextEditPlaceHolderHorizontalLayout.addWidget(self.lineEdit)

        self.enterButton = QtWidgets.QPushButton(self.chatTextEditPlaceHolder)

        self.enterButton.clicked.connect(self.sendParsing)

        # EnterButton
        self.enterButton.setText("Enter")

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enterButton.sizePolicy().hasHeightForWidth())
        self.enterButton.setSizePolicy(sizePolicy)

        # Add EnterButton to PlaceHolder
        self.chatTextEditPlaceHolderHorizontalLayout.addWidget(self.enterButton)

        # Add PlaceHolder to chatPage
        self.chatPageGridLayout.addWidget(self.chatTextEditPlaceHolder, 1, 0, 1, 1)

        # Add secondPage to mainWindowStatckedWidget
        self.mainWindow.addWidget(self.secondPage)

        self.secondPageHorizontalLayout.addWidget(self.userPage)
        self.secondPageHorizontalLayout.addWidget(self.SecondPage_Line)
        self.secondPageHorizontalLayout.addWidget(self.chatPage)

        # ThirdPage
        self.thirdPage = QtWidgets.QWidget()
        self.thirdPage.setStyleSheet(
                "#thirdPage {"
                "    background-color : \"white\";"
                "}")

        self.thirdPagHorizontalLayout = QtWidgets.QHBoxLayout(self.thirdPage)

        # ATeamPage
        self.ATeamPage = QtWidgets.QWidget(self.thirdPage)
        self.ATeamPage.setStyleSheet(
            "QWidget QWidget QPushButton {"
            "    Text-align : left;"
            "}")
        self.ATeamVerticalLayout = QtWidgets.QVBoxLayout(self.ATeamPage)
        self.ATeamTitle = QtWidgets.QWidget(self.ATeamPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ATeamTitle.sizePolicy().hasHeightForWidth())
        self.ATeamTitle.setSizePolicy(sizePolicy)

        self.ATeamTitleHorizontalLayout = QtWidgets.QHBoxLayout(self.ATeamTitle)
        self.ATeamTitleHorizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ATeamTitleHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.ATeamTitleHorizontalLayout.setSpacing(0)

        self.ATeamLabel = QtWidgets.QLabel(self.ATeamTitle)

        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.ATeamLabel.setFont(font)
        self.ATeamLabel.setStyleSheet("color : \"orange\";")
        self.ATeamTitleHorizontalLayout.addWidget(self.ATeamLabel)

        self.ATeamUpgradeButton = QtWidgets.QToolButton(self.ATeamTitle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ATeamUpgradeButton.sizePolicy().hasHeightForWidth())
        self.ATeamUpgradeButton.setSizePolicy(sizePolicy)
        self.ATeamUpgradeButton.setStyleSheet("background : \"transparent\";")

        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(".\\up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ATeamUpgradeButton.setIcon(icon6)
        self.ATeamUpgradeButton.setIconSize(QtCore.QSize(40, 40))
        self.ATeamUpgradeButton.setCheckable(False)
        self.ATeamUpgradeButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ATeamUpgradeButton.setObjectName("toolButton_21")
        self.ATeamTitleHorizontalLayout.addWidget(self.ATeamUpgradeButton)

        ATeamTitleSpacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ATeamTitleHorizontalLayout.addItem(ATeamTitleSpacer)

        self.ATeamMMR = QtWidgets.QLabel(self.ATeamTitle)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ATeamMMR.setFont(font)
        self.ATeamMMR.setObjectName("label_19")
        self.ATeamTitleHorizontalLayout.addWidget(self.ATeamMMR)
        self.ATeamVerticalLayout.addWidget(self.ATeamTitle)

        self.thirdPagHorizontalLayout.addWidget(self.ATeamPage)

        self.teamLine = QtWidgets.QFrame(self.thirdPage)
        self.teamLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.teamLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.thirdPagHorizontalLayout.addWidget(self.teamLine)

        # BTeamPage
        self.BTeamPage = QtWidgets.QWidget(self.thirdPage)
        self.BTeamPage.setStyleSheet(
            "QWidget QWidget QPushButton {\n"
            "    Text-align : left;\n"
            "}")
        self.BTeamVerticalLayout = QtWidgets.QVBoxLayout(self.BTeamPage)
        self.BTeamTitle = QtWidgets.QWidget(self.BTeamPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTeamTitle.sizePolicy().hasHeightForWidth())
        self.BTeamTitle.setSizePolicy(sizePolicy)

        self.BTeamTitleHorizontalLayout = QtWidgets.QHBoxLayout(self.BTeamTitle)
        self.BTeamTitleHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.BTeamTitleHorizontalLayout.setSpacing(0)

        self.BTeamLabel = QtWidgets.QLabel(self.BTeamTitle)

        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)

        self.BTeamLabel.setFont(font)
        self.BTeamLabel.setStyleSheet("color : \"dodgerblue\";")
        self.BTeamLabel.setObjectName("BTeamLabel")
        self.BTeamTitleHorizontalLayout.addWidget(self.BTeamLabel)

        self.BTeamUpgradeButton = QtWidgets.QToolButton(self.BTeamTitle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTeamUpgradeButton.sizePolicy().hasHeightForWidth())
        self.BTeamUpgradeButton.setSizePolicy(sizePolicy)
        self.BTeamUpgradeButton.setStyleSheet("background : \"transparent\";")

        self.BTeamUpgradeButton.setIcon(icon6)
        self.BTeamUpgradeButton.setIconSize(QtCore.QSize(40, 40))
        self.BTeamUpgradeButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.BTeamUpgradeButton.setObjectName("toolButton_32")
        self.BTeamTitleHorizontalLayout.addWidget(self.BTeamUpgradeButton)

        BTeamTitleSpacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.BTeamTitleHorizontalLayout.addItem(BTeamTitleSpacer)

        self.BTeamMMR = QtWidgets.QLabel(self.BTeamTitle)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BTeamMMR.setFont(font)
        self.BTeamMMR.setObjectName("label_20")
        self.BTeamTitleHorizontalLayout.addWidget(self.BTeamMMR)
        self.BTeamVerticalLayout.addWidget(self.BTeamTitle)

        self.thirdPagHorizontalLayout.addWidget(self.BTeamPage)

        self.mainWindow.addWidget(self.thirdPage)

        # Finishing by Pushing StackedLayout into verticalLayout
        self.verticalLayout.addWidget(self.mainWindow)
        self.gridLayout.addWidget(self.windowWidget, 0, 1, 1, 1)

        self.retranslateUI(window)
        self.variableMenu.setCurrentIndex(2)
        self.mainWindow.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUI(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Form"))
        self.addUserButton.setText(_translate("window", "인원추가"))
        self.mmrBalancingButton.setText(_translate("window", "MMR밸런싱"))
        self.randomTeamButton.setText(_translate("window", "랜덤팀구성"))
        self.clipboradButton.setText(_translate("window", "클립보드복사"))
        self.randomTeamButton2.setText(_translate("window", "랜덤팀구성"))
        self.lineEdit.setPlaceholderText(_translate("window", "[여기에 텍스트 입력]"))
        self.ATeamLabel.setText(_translate("window", "A팀"))
        self.ATeamUpgradeButton.setText(_translate("window", "전력강화"))
        self.ATeamMMR.setText(_translate("window", "추정 MMR"))
        self.BTeamLabel.setText(_translate("window", "B팀"))
        self.BTeamUpgradeButton.setText(_translate("window", "전력강화"))
        self.BTeamMMR.setText(_translate("window", "추정 MMR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QWidget()
    ui = UI_Window()
    ui.setupUI(window)
    ui.initSetting()
    window.show()
    sys.exit(app.exec_())
